### PR TITLE
fix(android): fix remote file path on Windows

### LINKED ISSUE #471: Pulling /sdcard/allure-results failed with vendor ADAM
**With vendor ADAM allure ondevice reports pull not work**

**To Reproduce**
Steps to reproduce the behaviour:
1. create default project
2. add allure-kotlin and configure it in tests
3. add marathon config
4. copy marathon cli 0.6.1 in root project folder
5. run from root project folder ./marathon-0.6.1/bin/marathon -m ./Marathonfile

Marathonfile - 
```
name: "testProject"
outputDir: "./marathon"
fallbackToScreenshots: false
strictMode: false
testOutputTimeoutMillis: 90000
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 10
  retryPerTestQuota: 2
vendorConfiguration:
  type: "Android"
  applicationApk: "app/build/outputs/apk/debug/app-debug.apk"
  testApplicationApk: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
  autoGrantPermission: false
  serialStrategy: "automatic"
  instrumentationArgs:
    debug: "false"
  applicationPmClear: false
  testApplicationPmClear: false
  vendor: ADAM
  allureConfiguration:
    enabled: true
  screenRecordConfiguration:
    preferableRecorderType: "video"
```
    
additional information - 
1. host OS - Windows 10
2. shell for commands - git bash
3. behavior - file of allure report created in "allure-device-results" but file is empty
   
**Expected behavior**
allure report successfully pulled from device to allure-device-results folder 
(same behavior like vendor DDMLIB (with DDMLIB it work))

**Logs and reports**
log - [log.txt](https://github.com/Malinskiy/marathon/files/6156741/log.txt)

**Devices (please complete the following information):**
 - Any default android emulator, i try on Pixel XL API 27

### PR DESCRIPTION
**Pull request by Malinskiy**
Fixes #471

### CODE REVIEW

File: vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamAndroidDevice.kt [hunk 1]
```diff
@@ -236,7 +236,7 @@ class AdamAndroidDevice(
                 mkdirs()
             }
             val localFile = File(localFileDirectory, file.name)
-            val remoteFilePath = "${file.directory}${File.separator}${file.name}"
+            val remoteFilePath = "${file.directory}/${file.name}"
```
Comment (tagantroy) [inline vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamAndroidDevice.kt:239]: Should we switch to Path.get to prevent similar issues in future?

**Review by tagantroy — APPROVED** [review]
