### PR TITLE
fix(android): handle special characters in the apk

### LINKED ISSUE #613: Marathon script fails if apk file contains brackets
Marathon script fails if testing apk file contains brackets.
**STR**:

1. Name the file so that the name includes brackets. For example: test(1).apk.
For this In _android.defaultConfig_ section of app level _build.gradle.kts_ add:
`setProperty("archivesBaseName", "test(1)")`
4. Run `./gradlew marathon`
5. See error in console: `com.malinskiy.adam.exception.RequestRejectedException: Unexpected exit code value pected '('`

Marathon version: **0.7.0**

**Expected behaviour:**
Escape brackets in apk file name.

### PR DESCRIPTION
**Pull request by Malinskiy**
Fixes #613

### CODE REVIEW

File: buildSrc/src/main/kotlin/Versions.kt [hunk 1]
```diff
@@ -5,7 +5,7 @@ object Versions {
     val coroutines = "1.5.2"
 
     val ddmlib = "30.0.2"
-    val adam = "0.4.3"
+    val adam = "0.4.4"
```
Comment (Malinskiy) [inline buildSrc/src/main/kotlin/Versions.kt:8]: New adam contains escaping for regular PushRequest, but not a CompatPushRequest

File: vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamAndroidDevice.kt [hunk 2]
```diff
@@ -258,7 +259,9 @@ class AdamAndroidDevice(
 
     override suspend fun installPackage(absolutePath: String, reinstall: Boolean, optionalParams: List<String>): String? {
         val file = File(absolutePath)
-        val remotePath = "${RemoteFileManager.TMP_PATH}/${file.name}"
+        //Very simple escaping for the name of the file
```
Comment (Malinskiy) [inline vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamAndroidDevice.kt:262]: This escaping will merely replace non-alphanum characters with `-`
