### PR TITLE
Fix ignoreFailures behaviour in gradle plugin

### LINKED ISSUE #255: IgnoreFailures doesn't work
When I launch marathon by gradle plugin. I set ignoreFailures with true. But it doesn't work.

image

image

When any test failed, gradle task failed too

### PR DESCRIPTION
**Pull request by Malinskiy**
Fixes #255

### CODE REVIEW

File: marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/MarathonRunTask.kt [hunk 1]
```diff
@@ -82,7 +82,8 @@ open class MarathonRunTask : DefaultTask(), VerificationTask {
 
         val success = Marathon(cnf).run()
 
-        if (!success) {
+        val shouldReportFailure = !cnf.ignoreFailures
```
Comment (tagantroy) [inline marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/MarathonRunTask.kt:85]: 👍

**Review by tagantroy — APPROVED** [review]
