### PR TITLE
Stabilise 0.6.0 adam

### LINKED ISSUE #436: ADAM can't install APK on some devices
**Describe the bug**
Trying new `ADAM` provider I start a usual test run on several devices. Marathon wasn't able to install apk on all devices although response from device was `Success`. Here sample from log:
```log
Success
 [0;39mcom.malinskiy.marathon.android.exception.InstallException: pkg: /data/local/tmp/debug.apk
	at com.malinskiy.marathon.android.AndroidAppInstaller$reinstall$2.invokeSuspend(AndroidAppInstaller.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Configuration of Marathonfile
```yaml
vendorConfiguration:
  androidSdk: "/opt/android/sdk"
  applicationApk: /some/path/to/debug/debug.apk
  testApplicationApk: /some/path/to/debug/debug-AndroidTest.apk
  vendor: ADAM
  type: "Android"
  autoGrantPermission: false
  applicationPmClear: true
  testApplicationPmClear: true
  serialStrategy: "ddms"
  screenRecordConfiguration:
    preferableRecorderType: "VIDEO"
name: "Tests"
outputDir: "./marathon"
filteringConfiguration:
  allowlist:
  - type: "composition"
    filters:
    - type: "package"
      regex: "heh\\.mda\\.feature.*"
    op: "UNION"
  blocklist: []
testOutputTimeoutMillis: 150000
debug: true
ignoreFailures: true
retryStrategy:
  type: "fixed-quota"
  totalAllowedRetryQuota: 65
  retryPerTestQuota: 1
```
2. Start marathon 

**Expected behavior**
Adam install apk on emulator 

**Logs and reports**
[marathon-adam.log](https://github.com/Malinskiy/marathon/files/5871849/marathon-adam.log)

**Devices (please complete the following information):**
 - Device: emulator
 - OS: Android API 23

**Additional context**

### PR DESCRIPTION
**Pull request by Malinskiy**
This PR stabilizes the adam Android vendor. List of issues:
* Adam 0.2.3 (Fix socket timeout for long running requests + USB transport)
* Force single kotlin version everywhere
* Update gradle to 6.8 and kotlin to 1.4.20
* Fix for suspend race condition in QueueActor
* Use new image capture adapters from adam
* New timeout configuration (adam specific)
* Measure file transfer speeds during pull/push
* Survive adb kill-server
* Fix allure legacy storage on API 29
* Fix AndroidAppInstaller for some devices
* Rotate screenshots based on initial device rotation

### CODE REVIEW

File: vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamDeviceProvider.kt [hunk 1]
```diff
@@ -127,7 +135,9 @@ class AdamDeviceProvider(
     override suspend fun terminate() {
         bootWaitContext.close()
         channel.close()
-        deviceEventsChannel.cancel()
+        synchronized(deviceEventsChannelLock) {
```
Comment (tagantroy) [inline vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamDeviceProvider.kt:138]: Can we use https://kotlinlang.org/docs/reference/coroutines/shared-mutable-state-and-concurrency.html#mutual-exclusion
instead of synchronized?

**Comment by Malinskiy** [comment]
Fixes #436

File: vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamDeviceProvider.kt [hunk 2]
```diff
@@ -51,6 +52,7 @@ class AdamDeviceProvider(
 
     private lateinit var client: AndroidDebugBridgeClient
     private lateinit var deviceEventsChannel: ReceiveChannel<List<Device>>
+    private val deviceEventsChannelLock = Object()
```
Comment (tagantroy) [inline vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamDeviceProvider.kt]: Do we need java synchronized here or https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.sync/-mutex/index.html makes more sense?

**Review by tagantroy — APPROVED** [review]

File: vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamDeviceProvider.kt (hunk 2 above)
Comment (Malinskiy) [reply vendor/vendor-android/adam/src/main/kotlin/com/malinskiy/marathon/android/adam/AdamDeviceProvider.kt]: Fixed
